// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiFurb.Infra.Contextos;

#nullable disable

namespace RestApiFurb.Infra.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestApiFurb.Dominio.Modelos.Comanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("DataAtivacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ATIVACAO")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_DESATIVACAO");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_FK");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("COMANDA", (string)null);
                });

            modelBuilder.Entity("RestApiFurb.Dominio.Modelos.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_PROCESSAMENTO");

                    b.Property<string>("Erro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ERRO");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAYLOAD");

                    b.Property<bool>("Processado")
                        .HasColumnType("bit")
                        .HasColumnName("PROCESSADO");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TIPO_EVENTO");

                    b.HasKey("Id");

                    b.ToTable("OUTBOX_MESSAGE", (string)null);
                });

            modelBuilder.Entity("RestApiFurb.Dominio.Modelos.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORIA");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CODIGO_BARRAS");

                    b.Property<DateTime>("DataAtivacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ATIVACAO")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_DESATIVACAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECO");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE_ESTOQUE");

                    b.HasKey("Id");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("RestApiFurb.Dominio.Modelos.ProdutoComanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COMANDA_FK");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PRODUTO_FK");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PRODUTO_COMANDA", (string)null);
                });

            modelBuilder.Entity("RestApiFurb.Dominio.Modelos.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("DataAtivacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ATIVACAO")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_DESATIVACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("RestApiFurb.Dominio.Modelos.Comanda", b =>
                {
                    b.HasOne("RestApiFurb.Dominio.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RestApiFurb.Dominio.Modelos.ProdutoComanda", b =>
                {
                    b.HasOne("RestApiFurb.Dominio.Modelos.Comanda", "Comanda")
                        .WithMany("ProdutosComanda")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RestApiFurb.Dominio.Modelos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("RestApiFurb.Dominio.Modelos.Comanda", b =>
                {
                    b.Navigation("ProdutosComanda");
                });
#pragma warning restore 612, 618
        }
    }
}
